name: MMLPhoto-Z寻参 (lp_zPDF)
program: train.py
method: grid
metric:
  goal: minimize
  name: best_val_mae_epoch
parameters:
  learn_rate:
    values:
      - 0.01
      - 0.005
      - 0.001
      - 0.0005
      - 0.0001
      - 1e-5
  cos_annealing_t_0:
    values:
      - 10
      - 30
      - 50
  cos_annealing_t_mult:
    values:
      - 1
      - 2
      - 3
  cos_annealing_eta_min:
    values:
      - 1e-12
